
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Dec 26 16:26:16 CET 2022
//----------------------------------------------------

package lexer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULTIPLY = 18;
  public static final int ELSE = 5;
  public static final int PLUS = 16;
  public static final int RBRACE = 29;
  public static final int RPAREN = 13;
  public static final int EQUAL = 22;
  public static final int NOTEQUAL = 23;
  public static final int IN = 10;
  public static final int WHILE = 6;
  public static final int RETURN = 9;
  public static final int IDENTIFIER = 3;
  public static final int GREATER = 24;
  public static final int INTCONST = 27;
  public static final int IF = 4;
  public static final int LBRACE = 28;
  public static final int LESSEQUAL = 21;
  public static final int LPAREN = 12;
  public static final int COLON = 14;
  public static final int COMMA = 15;
  public static final int EOF = 0;
  public static final int DIVIDE = 19;
  public static final int CHARCONST = 26;
  public static final int DEF = 8;
  public static final int MINUS = 17;
  public static final int PRINT = 2;
  public static final int error = 1;
  public static final int ASSIGNMENT = 11;
  public static final int FOR = 7;
  public static final int GREATEREQUAL = 25;
  public static final int LESS = 20;
}

